window.PNG_ARRAY = [
  // Food
  { name: 'cviacorn',      file: '../../images/cvipng/cviacorn.png',      category: 'food' },
  { name: 'cviapple',      file: '../../images/cvipng/cviapple.png',      category: 'food' },
  { name: 'cvibanana',     file: '../../images/cvipng/cvibanana.png',     category: 'food' },
  { name: 'cvibrocoli',    file: '../../images/cvipng/cvibrocoli.png',    category: 'food' },
  { name: 'cvicarrot',     file: '../../images/cvipng/cvicarrot.png',     category: 'food' },
  { name: 'cvicelery',     file: '../../images/cvipng/cvicelery.png',     category: 'food' },
  { name: 'cvigrape',      file: '../../images/cvipng/cvigrape.png',      category: 'food' },
  { name: 'cvistrawberry', file: '../../images/cvipng/cvistrawberry.png', category: 'food' },
  { name: 'cviwatermelon', file: '../../images/cvipng/cviwatermelon.png', category: 'food' },
  { name: 'cviorange',     file: '../../images/cvipng/cviorange.png',     category: 'food' },

  // Plants
  { name: 'cvibaobab',   file: '../../images/cvipng/cvibaobab.png',   category: 'plants' },
  { name: 'cvicactus',   file: '../../images/cvipng/cvicactus.png',   category: 'plants' },
  { name: 'cvifern',     file: '../../images/cvipng/cvifern.png',     category: 'plants' },
  { name: 'cvifir',      file: '../../images/cvipng/cvifir.png',      category: 'plants' },
  { name: 'cvitree',     file: '../../images/cvipng/cvitree.png',     category: 'plants' },
  { name: 'cvirose',     file: '../../images/cvipng/cvirose.png',     category: 'plants' },
  { name: 'cvitulip',    file: '../../images/cvipng/cvitulip.png',    category: 'plants' },
  { name: 'cvisunflower',file: '../../images/cvipng/cvisunflower.png',category: 'plants' },
  { name: 'cvimushroom', file: '../../images/cvipng/cvimushroom.png', category: 'plants' },

  // Animals
  { name: 'cvibear',      file: '../../images/cvipng/cvibear.png',      category: 'animals' },
  { name: 'cvicat',       file: '../../images/cvipng/cvicat.png',       category: 'animals' },
  { name: 'cvicow',       file: '../../images/cvipng/cvicow.png',       category: 'animals' },
  { name: 'cvidog',       file: '../../images/cvipng/cvidog.png',       category: 'animals' },
  { name: 'cvifox',       file: '../../images/cvipng/cvifox.png',       category: 'animals' },
  { name: 'cvifrog',      file: '../../images/cvipng/cvifrog.png',      category: 'animals' },
  { name: 'cvigecko',     file: '../../images/cvipng/cvigecko.png',     category: 'animals' },
  { name: 'cvigoat',      file: '../../images/cvipng/cvigoat.png',      category: 'animals' },
  { name: 'cvihorse',     file: '../../images/cvipng/cvihorse.png',     category: 'animals' },
  { name: 'cvipig',       file: '../../images/cvipng/cvipig.png',       category: 'animals' },
  { name: 'cvirabbit',    file: '../../images/cvipng/cvirabbit.png',    category: 'animals' },
  { name: 'cvisheep',     file: '../../images/cvipng/cvisheep.png',     category: 'animals' },
  { name: 'cvisnail',     file: '../../images/cvipng/cvisnail.png',     category: 'animals' },
  { name: 'cvicrocodile', file: '../../images/cvipng/cvicrocodile.png', category: 'animals' },

  // Birds
  { name: 'cviraven',   file: '../../images/cvipng/cviraven.png',   category: 'birds' },
  { name: 'cvipigeon',  file: '../../images/cvipng/cvipigeon.png',  category: 'birds' },
  { name: 'cvirooster', file: '../../images/cvipng/cvirooster.png', category: 'birds' },
  { name: 'cviturkey',  file: '../../images/cvipng/cviturkey.png',  category: 'birds' },
  { name: 'cviowl',     file: '../../images/cvipng/cviowl.png',     category: 'birds' },

  // Sea animals
  { name: 'cvicoral',     file: '../../images/cvipng/cvicoral.png',     category: 'sea animals' },
  { name: 'cviclownfish', file: '../../images/cvipng/cviclownfish.png', category: 'sea animals' },
  { name: 'cvicrab',      file: '../../images/cvipng/cvicrab.png',      category: 'sea animals' },
  { name: 'cvidolphin',   file: '../../images/cvipng/cvidolphin.png',   category: 'sea animals' },
  { name: 'cvifish',      file: '../../images/cvipng/cvifish.png',      category: 'sea animals' },
  { name: 'cvilobster',   file: '../../images/cvipng/cvilobster.png',   category: 'sea animals' },
  { name: 'cvimedusa',    file: '../../images/cvipng/cvimedusa.png',    category: 'sea animals' },
  { name: 'cvioctopus',   file: '../../images/cvipng/cvioctopus.png',   category: 'sea animals' },
  { name: 'cviseahorse',  file: '../../images/cvipng/cviseahorse.png',  category: 'sea animals' },
  { name: 'cvishark',     file: '../../images/cvipng/cvishark.png',     category: 'sea animals' },
  { name: 'cviwhale',     file: '../../images/cvipng/cviwhale.png',     category: 'sea animals' },

  // Insect
  { name: 'cviant',        file: '../../images/cvipng/cviant.png',        category: 'insect' },
  { name: 'cvibee',        file: '../../images/cvipng/cvibee.png',        category: 'insect' },
  { name: 'cvibutterfly',  file: '../../images/cvipng/cvibutterfly.png',  category: 'insect' },
  { name: 'cvispider',     file: '../../images/cvipng/cvispider.png',     category: 'insect' },
  { name: 'cvibeetle',     file: '../../images/cvipng/cvibeetle.png',     category: 'insect' },
  { name: 'cvicaterpillar',file: '../../images/cvipng/cvicaterpillar.png',category: 'insect' },
  { name: 'cviscarab',     file: '../../images/cvipng/cviscarab.png',     category: 'insect' },
  { name: 'cvidragonfly',  file: '../../images/cvipng/cvidragonfly.png',  category: 'insect' },
  { name: 'cvifirefly',    file: '../../images/cvipng/cvifirefly.png',    category: 'insect' },
  { name: 'cvigrasshopper',file: '../../images/cvipng/cvigrasshopper.png',category: 'insect' },
  { name: 'cviladybug',    file: '../../images/cvipng/cviladybug.png',    category: 'insect' },
  { name: 'cvimosquito',   file: '../../images/cvipng/cvimosquito.png',   category: 'insect' },

  // Vehicles
  { name: 'cvihelicopter', file: '../../images/cvipng/cvihelicopter.png', category: 'vehicles' },
  { name: 'cvitruck',      file: '../../images/cvipng/cvitruck.png',      category: 'vehicles' },
  { name: 'cvimotorcycle', file: '../../images/cvipng/cvimotorcycle.png', category: 'vehicles' },
  { name: 'cviboat',       file: '../../images/cvipng/cviboat.png',       category: 'vehicles' },
  { name: 'cvibigboat',    file: '../../images/cvipng/cvibigboat.png',    category: 'vehicles' },
  { name: 'cvikayak',      file: '../../images/cvipng/cvikayak.png',      category: 'vehicles' },
  { name: 'cviloader',     file: '../../images/cvipng/cviloader.png',     category: 'vehicles' },
  { name: 'cvibucket',     file: '../../images/cvipng/cvibucket.png',     category: 'vehicles' },

  // Shapes
  { name: 'cvicircle',      file: '../../images/cvipng/cvicircle.png',      category: 'shapes' },
  { name: 'cvidiamond',     file: '../../images/cvipng/cvidiamond.png',     category: 'shapes' },
  { name: 'cviheart',       file: '../../images/cvipng/cviheart.png',       category: 'shapes' },
  { name: 'cviminus',       file: '../../images/cvipng/cviminus.png',       category: 'shapes' },
  { name: 'cvioval',        file: '../../images/cvipng/cvioval.png',        category: 'shapes' },
  { name: 'cvipentagon',    file: '../../images/cvipng/cvipentagon.png',    category: 'shapes' },
  { name: 'cviplus',        file: '../../images/cvipng/cviplus.png',        category: 'shapes' },
  { name: 'cvirectangle',   file: '../../images/cvipng/cvirectangle.png',   category: 'shapes' },
  { name: 'cviblob',        file: '../../images/cvipng/cviblob.png',        category: 'shapes' },
  { name: 'cvispikyblob',   file: '../../images/cvipng/cvispikyblob.png',   category: 'shapes' },
  { name: 'cvisquare',      file: '../../images/cvipng/cvisquare.png',      category: 'shapes' },
  { name: 'cvistar',        file: '../../images/cvipng/cvistar.png',        category: 'shapes' },
  { name: 'cvitriangle',    file: '../../images/cvipng/cvitriangle.png',    category: 'shapes' },
  { name: 'cvix',           file: '../../images/cvipng/cvix.png',           category: 'shapes' },

  // Adapted sports
  { name: 'cvibasketball',         file: '../../images/cvipng/cvibasketball.png',         category: 'adapted sports' },
  { name: 'cviboccia',             file: '../../images/cvipng/cviboccia.png',             category: 'adapted sports' },
  { name: 'cviassistivesoccer',    file: '../../images/cvipng/cviassistivesoccer.png',    category: 'adapted sports' },
  { name: 'cvisledhockey',         file: '../../images/cvipng/cvisledhockey.png',         category: 'adapted sports' },
  { name: 'cvihorsetherapy',       file: '../../images/cvipng/cvihorsetherapy.png',       category: 'adapted sports' },
  { name: 'cvisassistiveswimming', file: '../../images/cvipng/cvisassistiveswimming.png', category: 'adapted sports' },
  { name: 'cviassistivebycicle',   file: '../../images/cvipng/cviassistivebycicle.png',  category: 'assistive materials' },

  // Assistive materials
  { name: 'cviwheelchair',        file: '../../images/cvipng/cviwheelchair.png',        category: 'assistive materials' },
  { name: 'cviwalker',            file: '../../images/cvipng/cviwalker.png',            category: 'assistive materials' },
  { name: 'cvieyegaze',           file: '../../images/cvipng/cvieyegaze.png',           category: 'assistive materials' },
  { name: 'cviswitch1',           file: '../../images/cvipng/cviswitch1.png',           category: 'assistive materials' },
  { name: 'cviswitch2',           file: '../../images/cvipng/cviswitch2.png',           category: 'assistive materials' },


  // School
  { name: 'cvibackpack',  file: '../../images/cvipng/cvibackpack.png',  category: 'school' },
  { name: 'cviagenda',    file: '../../images/cvipng/cviagenda.png',    category: 'school' },
  { name: 'cvibook',      file: '../../images/cvipng/cvibook.png',      category: 'school' },
  { name: 'cvidesk',      file: '../../images/cvipng/cvidesk.png',      category: 'school' },
  { name: 'cviclock',     file: '../../images/cvipng/cviclock.png',     category: 'school' },
  { name: 'cviheadphone', file: '../../images/cvipng/cviheadphone.png', category: 'school' },
  { name: 'cvilunchbox',  file: '../../images/cvipng/cvilunchbox.png',  category: 'school' },
  { name: 'cvischool',    file: '../../images/cvipng/cvischool.png',    category: 'school' },
  { name: 'cvilist',      file: '../../images/cvipng/cvilist.png',      category: 'school' },
  { name: 'cviscissors',  file: '../../images/cvipng/cviscissors.png',  category: 'school' },
  { name: 'cvichair',     file: '../../images/cvipng/cvichair.png',     category: 'school' },

  // Letter and number
  { name: 'cvia', file: '../../images/cvipng/cvia.png', category: 'letter and number' },
  { name: 'cvib', file: '../../images/cvipng/cvib.png', category: 'letter and number' },
  { name: 'cvic', file: '../../images/cvipng/cvic.png', category: 'letter and number' },
  { name: 'cvi0', file: '../../images/cvipng/cvi0.png', category: 'letter and number' },
  { name: 'cvi1', file: '../../images/cvipng/cvi1.png', category: 'letter and number' },
  { name: 'cvi2', file: '../../images/cvipng/cvi2.png', category: 'letter and number' },
  { name: 'cvi3', file: '../../images/cvipng/cvi3.png', category: 'letter and number' },
  { name: 'cvi4', file: '../../images/cvipng/cvi4.png', category: 'letter and number' },
  { name: 'cvi5', file: '../../images/cvipng/cvi5.png', category: 'letter and number' },
  { name: 'cvi6', file: '../../images/cvipng/cvi6.png', category: 'letter and number' },
  { name: 'cvi7', file: '../../images/cvipng/cvi7.png', category: 'letter and number' },
  { name: 'cvi8', file: '../../images/cvipng/cvi8.png', category: 'letter and number' },
  { name: 'cvi9', file: '../../images/cvipng/cvi9.png', category: 'letter and number' },
];
