const LECTURE_OCULAIRE_LESSONS = [
  {
    id: 'lecon-1-ma',
    title: 'Leçon 1 — a, m, ma',
    focus: 'Travailler a, m, ma et maman',
    graphemes: ['a', 'm'],
    keyboard: ['m', 'a'],
    targetWord: 'ma',
    activities: [
      {
        id: 'l1-phoneme-m',
        type: 'phonemic-awareness',
        prompt: 'Quel mot commence par /m/ ?',
        model: 'Écoute : maman commence par /m/. Soleil commence par /s/.',
        choices: ['maman', 'soleil'],
        answer: 'maman',
      },
      {
        id: 'l1-grapheme-m',
        type: 'grapheme-phoneme',
        prompt: 'Quelle lettre fait /m/ ?',
        model: 'm fait /m/.',
        choices: ['m', 's'],
        answer: 'm',
      },
      {
        id: 'l1-decode-ma',
        type: 'decoding',
        prompt: 'Où est ma ?',
        model: 'm fait /m/, a fait /a/, ensemble ça fait ma.',
        choices: ['ma', 'si'],
        answer: 'ma',
      },
      {
        id: 'l1-encode-ma',
        type: 'encoding',
        prompt: 'Écris ma.',
        model: 'Choisis m puis a, puis valide.',
        answer: 'ma',
      },
      {
        id: 'l1-comprehension-ma',
        type: 'comprehension',
        prompt: 'Qui commence par ma ?',
        model: 'Maman commence par ma.',
        choices: ['maman', 'vélo'],
        answer: 'maman',
      },
    ],
  },
  {
    id: 'lecon-2-mi',
    title: 'Leçon 2 — i, mi, ami',
    focus: 'Ajouter i et lire mi / ami',
    graphemes: ['a', 'm', 'i'],
    keyboard: ['m', 'a', 'i'],
    targetWord: 'mi',
    activities: [
      {
        id: 'l2-grapheme-i',
        type: 'grapheme-phoneme',
        prompt: 'Quelle lettre fait /i/ ?',
        model: 'i fait /i/.',
        choices: ['i', 'a'],
        answer: 'i',
      },
      {
        id: 'l2-decode-mi',
        type: 'decoding',
        prompt: 'Où est mi ?',
        model: 'm fait /m/, i fait /i/, ensemble ça fait mi.',
        choices: ['mi', 'ma'],
        answer: 'mi',
      },
      {
        id: 'l2-encode-mi',
        type: 'encoding',
        prompt: 'Écris mi.',
        model: 'Choisis m puis i.',
        answer: 'mi',
      },
    ],
  },
  {
    id: 'lecon-3-la',
    title: 'Leçon 3 — l, la, lama',
    focus: 'Ajouter l et lire la / lama',
    graphemes: ['a', 'm', 'i', 'l'],
    keyboard: ['l', 'a', 'm', 'i'],
    targetWord: 'la',
    activities: [
      {
        id: 'l3-grapheme-l',
        type: 'grapheme-phoneme',
        prompt: 'Quelle lettre fait /l/ ?',
        model: 'l fait /l/.',
        choices: ['l', 'm'],
        answer: 'l',
      },
      {
        id: 'l3-decode-la',
        type: 'decoding',
        prompt: 'Où est la ?',
        model: 'l fait /l/, a fait /a/, ensemble ça fait la.',
        choices: ['la', 'mi'],
        answer: 'la',
      },
      {
        id: 'l3-comprehension-lama',
        type: 'comprehension',
        prompt: 'Quel mot contient la ?',
        model: 'Lama contient la.',
        choices: ['lama', 'ami'],
        answer: 'lama',
      },
    ],
  },
  {
    id: 'lecon-4-sa',
    title: 'Leçon 4 — s, sa, si',
    focus: 'Ajouter s et comparer sa / si',
    graphemes: ['s', 'a', 'i'],
    keyboard: ['s', 'a', 'i'],
    targetWord: 'sa',
    activities: [
      {
        id: 'l4-grapheme-s',
        type: 'grapheme-phoneme',
        prompt: 'Quelle lettre fait /s/ ?',
        model: 's fait /s/.',
        choices: ['s', 'm'],
        answer: 's',
      },
      {
        id: 'l4-decode-sa',
        type: 'decoding',
        prompt: 'Où est sa ?',
        model: 's fait /s/, a fait /a/, ensemble ça fait sa.',
        choices: ['sa', 'si'],
        answer: 'sa',
      },
      {
        id: 'l4-encode-si',
        type: 'encoding',
        prompt: 'Écris si.',
        model: 'Choisis s puis i.',
        answer: 'si',
      },
    ],
  },
  {
    id: 'lecon-5-pa',
    title: 'Leçon 5 — p, pa, papa',
    focus: 'Ajouter p et lire pa / papa',
    graphemes: ['p', 'a'],
    keyboard: ['p', 'a'],
    targetWord: 'pa',
    activities: [
      {
        id: 'l5-grapheme-p',
        type: 'grapheme-phoneme',
        prompt: 'Quelle lettre fait /p/ ?',
        model: 'p fait /p/.',
        choices: ['p', 'l'],
        answer: 'p',
      },
      {
        id: 'l5-decode-pa',
        type: 'decoding',
        prompt: 'Où est pa ?',
        model: 'p fait /p/, a fait /a/, ensemble ça fait pa.',
        choices: ['pa', 'la'],
        answer: 'pa',
      },
      {
        id: 'l5-comprehension-papa',
        type: 'comprehension',
        prompt: 'Qui commence par pa ?',
        model: 'Papa commence par pa.',
        choices: ['papa', 'maman'],
        answer: 'papa',
      },
    ],
  },
];
